### ISSUE TITLE
Unit tests for NotesControllerTest fail

### ISSUE THREAD

**Issue by acmiyaguchi** [scalableinternetservices/MapKeep#18]
If `rake test` is run, all the current unit tests fail. We should get these unit tests running since travis-ci integration will be added in soon.

**Comment by DxTania** [comment]
I think it has to do with devise

**Comment by DxTania** [comment]
Specifically, we need to somehow have a user signed in for any of those tests to work

**Comment by DxTania** [comment]
I've almost got them all passing, just have to fix something about note parameters

**Comment by DxTania** [comment]
Pull request #19 fixes tests (And adds album stuff)
