### ISSUE TITLE
Test factories over test fixtures

### ISSUE THREAD

**Issue by acmiyaguchi** [scalableinternetservices/MapKeep#20]
I'm wondering if we should use test factories for our unit testing. This is for dealing with test data initialization.  `factory_girl` seems to be held in higher regard and is more widely used in practice than the built in test fixtures. 

See below link for an article discussing the benefits of factories. 

https://semaphoreci.com/blog/2014/01/14/rails-testing-antipatterns-fixtures-and-factories.html

**Comment by DxTania** [comment]
Good find. I need to start liking testing. lol

**Comment by DxTania** [comment]
Implemented in pull request #34
