### ISSUE TITLE
Album sidebar creation bugs

### ISSUE THREAD

**Issue by DxTania** [scalableinternetservices/MapKeep#72]
- Map does not load if user has no albums
- Cancel button submits the form

I've reverted it because it can interefere with out demo. Please fix and test extensively before merging.

**Comment by smhernandez** [comment]
Fixed the map loading, the sidebar given no albums, and formManager updating upon new albums. Put these changes into the branch where you placed the revert changes (revert-67-albums branch). I figured it might be better to keep the album changes on a new branch anyway. Let me know if the cancel button doesn't work for you still.
