### ISSUE TITLE
Adding a css framework

### ISSUE THREAD

**Issue by acmiyaguchi** [scalableinternetservices/MapKeep#8]
Currently we don't have css on our application. I think adding a gem for bootstrap would work.

**Comment by DxTania** [comment]
I kind of dislike bootstrap and think it just looks ugly, what about Foundation?

**Comment by DxTania** [comment]
I don't mind doing a lot of the styling either

**Comment by acmiyaguchi** [comment]
Foundation sounds like it would work well. I only have experience with bootstrap. Is it as easy to use as bootstrap, in terms of documentation and maintainability?

**Comment by DxTania** [comment]
Yeah, I think it is. Pretty simple to use, and has easy to read documentation. And I think Foundation makes it easier to create good looking sites that don't look like they were created by the same thing.

**Comment by acmiyaguchi** [comment]
Looks like this issue has been solved with pull request #11. Foundation it is, thanks Tania.
