### ISSUE TITLE
What database to use

### ISSUE THREAD

**Issue by DxTania** [scalableinternetservices/MapKeep#9]
I've been doing some research, and I think we need to figure out what database to use before we start really doing anything. Especially because we need something good with geo operations. I've heard MongoDB is really good for scaling with this, but MongoDB does not use active record (which is why we have to think about this now, we would have to change a lot if we choose a DB that doesn't use active records). There's also this article I found: http://ngauthier.com/2013/08/postgis-and-rails-a-simple-approach.html 
Which says it is possible to active record with PostGIS, a geospatial add-on for PostgreSQL. We could also ask the professor what he thinks would be the best method.

**Comment by DxTania** [comment]
It does look like MySQL has added some geo features I didn't know about. I'll have to look into it and see if I can find difference in performance between it and other dbs. Here's some info: http://www.percona.com/blog/2013/10/21/using-the-new-spatial-functions-in-mysql-5-6-for-geo-enabled-applications/

**Comment by acmiyaguchi** [comment]
This sounds like a good topic to do some rigorous performance testing on. We should find a suitable dataset for geospatial queries to test. The performance gain we get might not beat out the convenience of active record, but this seems like something we can document. 

 That or ask the professor on his opinion. That seems like a good option too.

**Comment by DxTania** [comment]
Ah good point. I'm just wondering how much work would go into switching around the DB (at least between active record and non-active record ones). Might be less than I think. We could probably easily do the performance testing on at least the SQL based ones though.

**Comment by acmiyaguchi** [comment]
Going from relational to nonrelational might be a problem, but models wouldnt have to change all that much. And our application is simple enough where a transition would only take sprint or so to do. However, I think we should stick to a relational database that is supported by active directory for the sake of having plenty of support and documentation around.

**Comment by DxTania** [comment]
Alright, I'm cool with that as long as we look into it at some point later
